services:
  postgres:
    image: postgres
    container_name: flask_assignment
    restart: unless-stopped

    ports:
      - "5433:5432"
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-db 
    
    volumes:
      - flask_data:/var/lib/postgresql

volumes:
  flask_data: